<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout</name>
   <tag></tag>
   <elementGuidId>a9cd75f7-4643-4230-a162-0d9f91f63c47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.label-logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div[3]/a/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b1b14f33-1bbb-41e6-a4a6-884c05628eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-logout</value>
      <webElementGuid>84d41062-7843-42b0-b3c1-6e9b56f08ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>1d8249b1-9dd3-43b0-8b73-f7c2822c1a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-body __className_b2e2fc theme-gray-green&quot;]/div[1]/div[@class=&quot;web:flex web:flex-1 app-container with-header-navbar bg-main rounded-[32px] overflow-hidden p-0 pb-2 web:pb-0 web:mb-2&quot;]/div[@class=&quot;w-full h-full web:relative&quot;]/div[@class=&quot;main-container mobile:with-header-navbar p-0&quot;]/div[@class=&quot;wrapper-content w-full h-full overflow-hidden mobile:px-6 mobile:pt-4 web:px-12 web:pt-6&quot;]/div[@class=&quot;relative h-full&quot;]/div[@class=&quot;absolute bottom-0 left-0 right-0 bg-main mobile:py-6&quot;]/a[1]/div[@class=&quot;flex items-center gap-2 cursor-pointer&quot;]/div[@class=&quot;label-logout&quot;]</value>
      <webElementGuid>1ad51de7-28be-4b74-8560-4acea3222dc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/a/div/div</value>
      <webElementGuid>de8f6a79-9304-43e6-81c4-390fc9117395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>0255acb4-75fe-44f9-a971-daa7c8600d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
