<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_BCA</name>
   <tag></tag>
   <elementGuidId>bcee0983-fbd7-44a7-91bf-182b77e05d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.flex.items-center.justify-between.text-skin-secondary.text-sm.font-normal.py-2.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a75e9c14-c1b6-43a2-a9e2-334df3686a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>bca</value>
      <webElementGuid>f603b278-b2f3-49bb-abf7-34dd229c2814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between text-skin-secondary text-sm font-normal py-2 cursor-pointer</value>
      <webElementGuid>ce2a91ff-7abe-48dc-a313-e971cded6bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BCA</value>
      <webElementGuid>b8b7b7c1-7e3c-415c-8953-237aa6d0c873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-body __className_b2e2fc theme-gray-violet&quot;]/div[1]/div[@class=&quot;web:flex web:flex-1 app-container with-header-navbar bg-main rounded-[32px] overflow-hidden p-0 pb-2 web:pb-0 web:mb-2&quot;]/div[@class=&quot;w-full h-full web:relative&quot;]/div[@class=&quot;absolute z-[101] top-0 bottom-0 left-0 right-0 mobile:h-fit mobile:mt-[50px] mobile:px-2&quot;]/div[@class=&quot;mobile:bg-body opacity-100 scale-100&quot;]/div[@class=&quot;main-container mobile:with-header-navbar p-0 web:backdrop-brightness-50&quot;]/div[@class=&quot;wrapper-content w-full h-full mobile:px-4 pt-10 web:pb-5 mobile:pb-3 py-0 web:bg-transparent&quot;]/div[@class=&quot;relative flex h-full overflow-hidden web:items-center&quot;]/div[@class=&quot;w-full h-full web:max-w-md mx-auto web:bg-main web:p-6 web:pb-0 web:rounded-[20px]&quot;]/div[@class=&quot;h-[calc(100%-160px)] web:h-[calc(100%-180px)] overflow-y-auto no-scrollbar mobile:px-2&quot;]/div[@class=&quot;capitalize mb-9&quot;]/label[@class=&quot;flex items-center justify-between text-skin-secondary text-sm font-normal py-2 cursor-pointer&quot;]</value>
      <webElementGuid>205ebc78-986d-4abd-aecb-5dcd77afe0d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>dfa13d92-9dbe-45f6-a6bc-349721463f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'BCA' or . = 'BCA')]</value>
      <webElementGuid>dd5afed9-7c3a-4313-91d3-f1523dfe8ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
