<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selected-bank</name>
   <tag></tag>
   <elementGuidId>01a9fded-07b9-4999-a463-8432c7dd710c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BCA-LABALABA-11111111111111111111</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BCA-LABALABA-11111111111111111111']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ab02f80-058c-40b6-9e71-183b35b2137c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>52947dad-75c7-40e2-93c4-fd1b729ac39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BCA-LABALABA-11111111111111111111</value>
      <webElementGuid>72330654-0ea1-4599-97b0-07babb026003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>645f12aa-f017-46ea-86ba-24b798fa4905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BCA-LABALABA-11111111111111111111</value>
      <webElementGuid>0f9ec0f0-ec6b-462b-8986-d9733a19cbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selected-bank</value>
      <webElementGuid>18a75db8-290e-4afd-bd34-547cbafb9ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BCA-LABALABA-11111111111111111111&quot;)</value>
      <webElementGuid>58296c9c-b5d0-47ae-833e-71aba9a8c7d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BCA-LABALABA-11111111111111111111']</value>
      <webElementGuid>5ced50b6-dad6-4e69-bfbb-fafbd1201b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>55f4113c-a97d-495b-beff-bf7836754507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BCA-LABALABA-11111111111111111111' and @type = 'radio' and @name = 'selected-bank']</value>
      <webElementGuid>0d4ccc86-c08b-4916-8a94-786447cc7913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
