<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_account_name</name>
   <tag></tag>
   <elementGuidId>6a77787b-6ca9-4cf0-bc2c-ba5db046864b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe94b747-58d9-47ad-a137-b1871843be83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>account_name</value>
      <webElementGuid>8a0e8780-d4ea-49b2-a00b-83a55359973c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account_name</value>
      <webElementGuid>3aedc2df-ae38-4264-b233-a2506f551cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account name</value>
      <webElementGuid>c0ee3af8-bf90-4439-8d9d-665667f1317c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-skin-input rounded-full px-[23px] h-10 w-full text-xs border border-brand-input ring-0 outline-none undefined focus:border-brand-primary focus:ring-brand-primary transition-all</value>
      <webElementGuid>cf8838c2-c535-488e-9e6b-078ee12da314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce6ada91-4ab6-4108-ad78-11869efc0de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>906ec343-f5e9-4999-8845-400e58141881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f113d17-a2aa-4ab4-9b10-854674389ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>f687ba87-d903-4aa6-97ad-7ffdca8dda07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f31a1c7c-987f-45bf-9710-3b5e02b76ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_name</value>
      <webElementGuid>5fca570c-4d7a-442d-a2b4-ce7843a81b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_name&quot;)</value>
      <webElementGuid>226480e7-7436-4088-9213-aee9409f3447</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account_name']</value>
      <webElementGuid>0b05a9b7-44e9-4a70-9641-f18be3812bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>798fbfe6-3bca-4548-8634-1c1a4bd92492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'account_name' and @placeholder = 'Account name' and @type = 'text' and @name = 'account_name']</value>
      <webElementGuid>0daa5ae3-c963-4626-b8da-7eebeabf19af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
