<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selected-bank</name>
   <tag></tag>
   <elementGuidId>c9e3faa4-bbe2-46cf-b51d-2843ac70a536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bca</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bca']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edcca7c7-f7aa-4357-a9c9-14da3489ef4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio </value>
      <webElementGuid>2115cea5-b229-4d8e-86fc-7b16e83be5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bca</value>
      <webElementGuid>5dfe514b-2c6b-4c40-897d-18d6d5a4011c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>98afdf69-91b5-4fec-ab54-7829d3f5c0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>bca</value>
      <webElementGuid>7ee85d01-2f48-43e8-ad72-21a5b94d4033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selected-bank</value>
      <webElementGuid>afd5e9e0-7099-4846-89e0-78a5ec12795b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bca&quot;)</value>
      <webElementGuid>af5ffbd1-64d1-4218-984a-400a28ff176a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bca']</value>
      <webElementGuid>e2ce0500-3eab-455f-9aec-d7d378e779a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/input</value>
      <webElementGuid>494220a4-e07e-4faa-9777-cd27825f2ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bca' and @type = 'radio' and @name = 'selected-bank']</value>
      <webElementGuid>e07a311f-9e01-47ae-a186-0d87575661c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
